version: "3"
services:
  web:
    #
    image: jetbrains/upsource:2017.1.1922
    deploy:
      replicas: 1
    config:
      - my_config
      - my_other_config
    configs:
      my_config:
        file: ./my_config.txt
      my_other_config:
        external: true
      rts:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: